import os
import sys

env=DefaultEnvironment().Clone()
LIB_DIR=os.environ['LIB_DIR'];

SOURCES=Glob('curl/lib/*.c') \
  +  Glob('curl/lib/vauth/*.c') \
  +  Glob('curl/src/*.c') \
  + Glob('curl/lib/vtls/*.c')

env.Library(os.path.join(LIB_DIR, 'curl'), SOURCES);
