import os
import sys

env=DefaultEnvironment().Clone()
LIB_DIR=os.environ['LIB_DIR'];

env['CPPPATH'] = env['CPPPATH'] + [
  os.path.join('.', 'mbedtls/crypto/library'),
  os.path.join('.', 'mbedtls/crypto/include/'),
  os.path.join('.', 'mbedtls/include'),
  os.path.join('.', 'mbedtls/library')
]

SOURCES=Glob('mbedtls/library/*.c') 

env.Library(os.path.join(LIB_DIR, 'tls'), SOURCES);
